### ISSUE TITLE
Add code to throw an SBOL validation exception for rule 12302 for GenericTopLevel objects

### ISSUE THREAD

**Issue by zgzn** [SynBioDex/libSBOLj#308] opened 2016-03-07 22:49 UTC

**Comment by cjmyers** [comment] 2016-03-11 00:13
I don't think this can be checked in libSBOLj because I think the parser will catch any violations first.

**Comment by cjmyers** [comment] 2016-03-11 19:44
I think the spirit of this rule is violated when the tag is not in a defined namespace. The problem is the parser returns the same error whether this happens for an annotation or a genericTopLevel.  If we could get the parser to return a different message based on context, we could give a different message.  

The message also is not great.  We might want to tweak this to better indicate what is wrong.  Should add a specification tracker item for this one.

**Comment by cjmyers** [comment] 2016-03-11 19:48
I think 10214, 12201, and 12302 may all overlap at this time.

**Comment by cjmyers** [comment] 2016-03-21 19:27
Worked out how to check this with Goksel.  Implemented and tested.

**Closed by cjmyers** 2016-03-21 19:27 UTC
Labels: change, question
